# Generated by Django 6.0.3 on 2026-03-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Carné de Extranjería')], default='DNI', max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('idioma_materno', models.CharField(choices=[('CASTELLANO', 'Castellano'), ('QUECHUA', 'Quechua'), ('AIMARA', 'Aimara'), ('ASHANINKA', 'Asháninka'), ('OTRO', 'Otro')], default='CASTELLANO', max_length=20)),
                ('idioma_materno_otro', models.CharField(blank=True, max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=120)),
                ('distrito_nacimiento', models.CharField(max_length=120)),
                ('provincia_nacimiento', models.CharField(max_length=120)),
                ('departamento_nacimiento', models.CharField(max_length=120)),
                ('pais_nacimiento', models.CharField(default='Perú', max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('es_menor_edad', models.BooleanField(default=False)),
                ('tutor_apellidos', models.CharField(blank=True, max_length=150)),
                ('tutor_nombres', models.CharField(blank=True, max_length=150)),
                ('tutor_numero_documento', models.CharField(blank=True, max_length=20)),
                ('tutor_tipo_parentesco', models.CharField(blank=True, max_length=100)),
                ('institucion_procedencia', models.CharField(max_length=255)),
                ('anio_egreso', models.PositiveIntegerField()),
                ('gestion_institucion', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], max_length=20)),
                ('direccion_institucion', models.CharField(max_length=255)),
                ('distrito_institucion', models.CharField(max_length=120)),
                ('provincia_institucion', models.CharField(max_length=120)),
                ('departamento_institucion', models.CharField(max_length=120)),
                ('pais_institucion', models.CharField(default='Perú', max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'postulante',
                'verbose_name_plural': 'postulantes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_informacion_admision', models.CharField(blank=True, max_length=150)),
                ('codigo_voucher_pago', models.CharField(max_length=50, unique=True)),
                ('codigo_postulante', models.CharField(max_length=30, unique=True)),
                ('numero_inscripcion', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_REVISION', 'En revisión'), ('OBSERVADO', 'Observado'), ('VALIDADO', 'Validado')], default='REGISTRADO', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('bloqueada', models.BooleanField(default=False)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='admision.convocatoria')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admision.modalidadpostulacion')),
                ('primera_opcion_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_primera_opcion', to='admision.programaestudio')),
                ('segunda_opcion_programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_segunda_opcion', to='admision.programaestudio')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='postulantes.postulante')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('postulante', 'convocatoria'), name='unique_postulante_convocatoria')],
            },
        ),
    ]
