# Generated by Django 6.0.3 on 2026-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='correo_enviado',
            field=models.BooleanField(default=False, verbose_name='Correo enviado'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('OBSERVADO', 'Observado'), ('VALIDADO', 'Validado')], default='REGISTRADO', max_length=20),
        ),
    ]
