# Generated by Django 6.0.3 on 2026-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_inscripcion_correo_enviado_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='ficha_pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
