# Generated by Django 6.0.3 on 2026-03-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0003_inscripcion_ficha_pdf_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='ficha_pdf_path',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ficha_drive_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ficha_drive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
