# Generated by Django 6.0.3 on 2026-03-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('extensiones_permitidas', models.CharField(default='pdf,jpg,jpeg,png', max_length=100)),
                ('tamano_max_mb', models.PositiveIntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_guardado', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('drive_url', models.URLField(blank=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255)),
                ('observacion', models.TextField(blank=True, help_text='Observación del validador si el documento no es válido')),
                ('valido', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='postulantes.inscripcion')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'documento de inscripción',
                'verbose_name_plural': 'documentos de inscripción',
                'ordering': ['-fecha_subida'],
                'constraints': [models.UniqueConstraint(fields=('inscripcion', 'tipo_documento'), name='unique_documento_por_tipo_inscripcion')],
            },
        ),
    ]
